apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: eryk
  labels:
    app: example
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
