apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
  namespace: eryk
  labels:
    app: example
spec:
  containers:
    - name: test-container
      envFrom:
        - secretRef:
            name: secret-object
      image: nginx:1.25
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
