apiVersion: v1
kind: Pod
metadata:
  name: example-pod-with-secret
  namespace: eryk
  labels:
    app: example
spec:
  containers:
    - name: test-container
      envFrom:
        - secretRef:
            name: mysecret
      image: nginx:1.25
      volumeMounts:
        - name: data
          mountPath: /etc/data
          readOnly: true
      volumes:
        - name: data
          configMap:
            name: simple-cm
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
