apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: eryk
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - while true; do sleep 3600; done
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
