apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: eryk
spec:
  containers:
  - name: busybox
    image: busybox:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "300m"
